load 18_2_2014_samples

dyskinetic_samples = {'moderate_stand_finger_left', ...
                      'moderate_stand_finger_right', ...
                      'moderate_stand_handopen_left',...
                      'moderate_stand_handopen_right', ...
                      'moderate_stand_supination_left', ...
                      'moderate_stand_supination_right',...
                      'moderate_stand_still'};

normal_samples = {'healthy_stand_finger_left', ...
                      'healthy_stand_finger_right', ...
                      'healthy_stand_handopen_left',...
                      'healthy_stand_handopen_right', ...
                      'healthy_stand_supination_left', ...
                      'healthy_stand_supination_right',...
                      'healthy_stand_still'};

[dys_sc1, dys_sc2, norm_sc1, norm_sc2] = compareTwoStates (dyskinetic_samples, normal_samples, joints.SPINE, 200);
%%


dyskinetic_samples = {'moderate_finger_left', ...
                      'moderate_finger_right', ...
                      'moderate_handopen_left',...
                      'moderate_handopen_right', ...
                      'moderate_supination_left', ...
                      'moderate_supination_right', ...
                      'moderate_sit_still'};

normal_samples = {'healthy_finger_left', ...
                      'healthy_finger_right', ...
                      'healthy_handopen_left', ...
                      'healthy_handopen_right', ...
                      'healthy_drink_left', ...
                      'healthy_drink_right', ...
                      'healthy_sit_still'};

[dys_sc1, dys_sc2, norm_sc1, norm_sc2] = compareTwoStates (dyskinetic_samples, normal_samples, joints.KNEERIGHT, 200);
